// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

enum LogType {
  Execution,
  Deposit,
  Withdraw,
  Refund
}

enum RoleType {
  None,
  Operator
}
