// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ShamanConfig } from "./tables/ShamanConfig.sol";
import { Shamans } from "./tables/Shamans.sol";
import { ShamanTransactions } from "./tables/ShamanTransactions.sol";
import { Roles } from "./tables/Roles.sol";
