// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IShamanSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IShamanSystem {
  function createShaman(uint256 initialDeposit, string memory metadataURI) external;

  function updateShamanMetadata(bytes32 shamanId, string memory metadataURI) external;

  function cancelShaman(bytes32 shamanId) external;

  function executeShaman(bytes32 shamanId, uint256 cost, address target, bytes memory data) external;

  function fundShaman(bytes32 shamanId, uint256 amount) external;
}
